services:
  # PatWos - Api: my api for my portfolio
  patwos-api:
    container_name: patwos-api
    image: ghcr.io/wosiu6/patwos-api:latest
    profiles: ["apps", "all"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
      - t3_proxy
    ports:
      - "${PATWOS_API_PORT}:8080"
    depends_on:
      patwos-api-db:
        condition: service_healthy
    healthcheck:
      disable: false
    volumes:
      - ./data/logs:/app/logs
      - ./data/uploads:/app/uploads
      - ./data/cache:/app/cache
    environment:
      DB_PASSWORD: ${PATWOS_API_DB_PASSWORD}
      DB_HOST: ${PATWOS_API_DB_HOST}
      DB_USER: ${PATWOS_API_DB_USER}
      DB_NAME: ${PATWOS_API_DB_NAME}
      API_PORT: ${PATWOS_API_PORT}
      GIN_MODE: release
      ALLOWED_ORIGINS: ${PATWOS_API_ALLOWED_ORIGINS}
      MAX_REQUEST_SIZE: ${PATWOS_API_MAX_REQUEST_SIZE}
      JWT_SECRET: ${PATWOS_API_JWT_SECRET}

  # PostgreSQL - Database for Patwos-api
  patwos-api-db:
    container_name: patwos-api-db
    image: postgres:17.6-alpine3.22
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${PATWOS_API_DB_NAME} -U $${PATWOS_API_DB_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    networks:
      - default
    ports:
      - "$PATWOS_API_DB_PORT:5432"
    command: -c max_connections=200
    volumes:
      - $DOCKERDIR/appdata/patwos-api-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$PATWOS_API_DB_NAME
      - POSTGRES_USER=$PATWOS_API_DB_USER
      - POSTGRES_PASSWORD=$PATWOS_API_DB_PASSWORD

networks:
  default:
    driver: bridge
  t3_proxy:
    external: true

  